import type { FoodType } from "./types";

export const GAME_CONFIG = {
  PLAYER_COUNT: 4,
  FOOD_TYPES: ["A", "B", "C", "D"] as const satisfies readonly FoodType[],
  INITIAL_CASH: 100,
  INITIAL_UNITS_PER_FOOD_TYPE: 100,
  INITIAL_UNITS_PER_PLAYER: 100,
  GAME_DURATION_SECONDS: 180,
  PRODUCTION_PER_SECOND: 2,
  CONSUMPTION_PER_REQUIRED_FOOD_PER_SECOND: 1,
  MIN_PRICE: 0,
  MIN_ORDER_QUANTITY: 1,
  MAX_OPEN_ORDERS_PER_PLAYER: 50,
  MAX_NEW_ORDERS_PER_PLAYER_PER_SECOND: 10,
  MAX_CANCELS_PER_PLAYER_PER_SECOND: 20,
  DISCONNECT_GRACE_SECONDS: 15,
  RECENT_TRADES_LIMIT: 20,
  EVENT_LOG_LIMIT: 100,
  PUBLIC_ORDER_BOOK_DEPTH: 10,
} as const;
